DROP TABLE MEMBER1;
CREATE TABLE MEMBER1 (
	MNO NUMBER PRIMARY KEY,
	MID VARCHAR2(20) NOT NULL,
	MNAME VARCHAR2(20)
);

DROP SEQUENCE MEMBER1_SEQ;
CREATE SEQUENCE MEMBER1_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 999999
NOCYCLE
NOCACHE;

INSERT INTO MEMBER1 (MNO, MID, MNAME) VALUES (MEMBER1_SEQ.NEXTVAL, 'emily', '에밀리');
INSERT INTO MEMBER1 (MNO, MID, MNAME) VALUES (MEMBER1_SEQ.NEXTVAL, 'alice', '앨리스');
COMMIT
